# Generated by Django 3.2.16 on 2023-02-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(default='', max_length=64, verbose_name='文献名称')),
                ('page_id', models.SmallIntegerField(default=1, verbose_name='页码')),
                ('page_img_num', models.SmallIntegerField(default=0, verbose_name='页面图片数')),
                ('txt_content', models.TextField(blank=True, null=True, verbose_name='文本内容')),
                ('img_content', models.TextField(blank=True, null=True, verbose_name='图片内容')),
            ],
            options={
                'verbose_name_plural': '文献内容',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('avatar', models.FileField(default='/default.jpg', upload_to='./avatars', verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '平台用户',
            },
        ),
        migrations.CreateModel(
            name='MeDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='文献名称')),
                ('relscore', models.FloatField(default=0, verbose_name='相关性得分')),
                ('clkscore', models.FloatField(default=0, verbose_name='点击量得分')),
                ('fedbakscore', models.FloatField(default=0, verbose_name='用户反馈得分')),
                ('allscore', models.FloatField(default=0, verbose_name='总分')),
                ('language', models.CharField(default='中文', max_length=16, verbose_name='语言')),
                ('date', models.DateField(default='2023-02-19', verbose_name='日期')),
                ('docfile', models.FileField(default='', upload_to='./docs', verbose_name='文献')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medocsys.user', verbose_name='贡献者')),
            ],
            options={
                'verbose_name_plural': '文献',
            },
        ),
    ]
