# Generated by Django 3.2.16 on 2023-02-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medocs',
            name='language',
            field=models.SmallIntegerField(choices=[(1, '中文'), (2, '英文')], default=1, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='medocs',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medocsys.user', verbose_name='贡献者'),
        ),
    ]
