# Generated by Django 3.2.16 on 2023-02-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0002_auto_20230219_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctxt',
            name='img_content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='图片内容'),
        ),
        migrations.AlterField(
            model_name='doctxt',
            name='txt_content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='文本内容'),
        ),
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-02-20', verbose_name='日期'),
        ),
    ]
