# Generated by Django 3.2.16 on 2023-02-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0003_auto_20230220_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctxt',
            name='page_img_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='页面图片数'),
        ),
    ]
