# Generated by Django 3.2.16 on 2023-02-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0004_alter_doctxt_page_img_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocImgTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(default='', max_length=64, verbose_name='文献名称')),
                ('page_id', models.SmallIntegerField(default=1, verbose_name='页码')),
                ('page_img_num', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='页面图片数')),
                ('img_content', models.TextField(blank=True, default='', null=True, verbose_name='图片内容')),
            ],
            options={
                'verbose_name_plural': '文献图片内容',
            },
        ),
        migrations.AlterModelOptions(
            name='doctxt',
            options={'verbose_name_plural': '文献文本内容'},
        ),
        migrations.RemoveField(
            model_name='doctxt',
            name='img_content',
        ),
        migrations.RemoveField(
            model_name='doctxt',
            name='page_img_num',
        ),
    ]
