# Generated by Django 3.2.16 on 2023-02-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0005_auto_20230220_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-02-21', verbose_name='日期'),
        ),
    ]
