# Generated by Django 3.2.16 on 2023-02-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0006_alter_medocs_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docimgtxt',
            options={'verbose_name': '文献图片内容', 'verbose_name_plural': '文献图片内容'},
        ),
        migrations.AlterModelOptions(
            name='doctxt',
            options={'verbose_name': '文献文本内容', 'verbose_name_plural': '文献文本内容'},
        ),
        migrations.AlterModelOptions(
            name='medocs',
            options={'verbose_name': '文献', 'verbose_name_plural': '文献'},
        ),
        migrations.AlterField(
            model_name='medocs',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='./docs', verbose_name='文献'),
        ),
    ]
