# Generated by Django 3.2.16 on 2023-02-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0007_auto_20230221_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-02-23', verbose_name='日期'),
        ),
    ]
