# Generated by Django 3.2.16 on 2023-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0008_alter_medocs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-02-25', verbose_name='日期'),
        ),
    ]
