# Generated by Django 3.2.16 on 2023-02-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0009_alter_medocs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docimgtxt',
            name='doc_name',
            field=models.CharField(default='', max_length=128, verbose_name='文献名称'),
        ),
        migrations.AlterField(
            model_name='doctxt',
            name='doc_name',
            field=models.CharField(default='', max_length=128, verbose_name='文献名称'),
        ),
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-02-26', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='medocs',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='文献名称'),
        ),
    ]
