# Generated by Django 3.2.16 on 2023-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0011_alter_medocs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-02-28', verbose_name='日期'),
        ),
    ]
