# Generated by Django 3.2.16 on 2023-03-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0012_alter_medocs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medocs',
            name='category',
            field=models.CharField(default='', max_length=128, verbose_name='文献种类'),
        ),
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-03-07', verbose_name='日期'),
        ),
    ]
