# Generated by Django 3.2.16 on 2023-04-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medocsys', '0013_auto_20230307_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='medocs',
            name='cover',
            field=models.FileField(default='/default.jpg', upload_to='./covers', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-04-02', verbose_name='日期'),
        ),
    ]
