# Generated by Django 3.2.16 on 2023-04-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medocsys', '0014_auto_20230402_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medocs',
            name='cover',
            field=models.CharField(default='default.jpg', max_length=128, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-04-03', verbose_name='日期'),
        ),
    ]
