# Generated by Django 3.2.16 on 2023-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medocsys', '0016_user_read_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateField(default='2023-04-03', verbose_name='注册日期'),
        ),
    ]
