# Generated by Django 3.2.18 on 2023-09-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocsys', '0017_user_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medocs',
            name='date',
            field=models.DateField(default='2023-09-20', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateField(default='2023-09-20', verbose_name='注册日期'),
        ),
    ]
